### ISSUE TITLE
No Read Permissions

### ISSUE THREAD

**Issue by philiparthurmoore** [Automattic/underscores.me#53] opened 2017-06-22 08:15 UTC
Moved over from https://github.com/Automattic/_s/issues/1128.

**Comment by davidakennedy** [comment] 2017-06-22 19:58
Hey @cesarcopi, I can't seem to reproduce this locally on a server. Anything special about the server you tried on?

**Comment by cesarcopi** [comment] 2017-06-25 15:11
No, nothing special. I downloaded the custom template from their website http://underscores.me/
and I installed the template in local

**Comment by davidakennedy** [comment] 2017-06-27 22:35
@cesarcopi Thanks for reporting back. I tried on a few different local installs, as well as a live sever, and can't reproduce this. I'm going to close it, but will be mindful of this if it pops up again. We can always reopen and try to nail it down if we get more details.

**Closed by davidakennedy** 2017-06-27 22:35 UTC

**Comment by cristacheda** [comment] 2017-12-11 15:12
Hello! I've been having the same issue for a few months now. These are the steps that I take for each and every project:

1. Generate new theme on underscores.me
2. Unzip theme into WordPress installation (for local development I'm using Vagrant with Scotch Box)
3. Code the theme and test it locally
4. Upload the website on a shared Linux server (from a local company - already checked the issue with them, they do not rewrite permissions on upload)
5. Fix the permissions manually from cPanel File Manager

From what I observed only the theme folder and the initial folders within have this issue. The folders that I create during the development process have the right permissions.

**Comment by cesarcopi** [comment] 2017-12-19 06:28
You can use this commands from the console:

**For Files**
`find . -type f -print0 | xargs -0 chmod 644`

**For Folders**
`find . -type d -print0 | xargs -0 chmod 755`

**Comment by grappler** [comment] 2017-12-26 21:53
@cristacheda and @cesarcopi What permissions do the files and folder have when you first download the zip file?

What OS are you using?

I tried to replicate the issue on a mac and failed to too.
